import React from 'react'
import Testimonial from './Testimonial';


export const metadata = {
    title: "Testimonial  || Ozark Company",
    description: "Generated by create next app",
};


const page = () => {
    return (
        <>
            <Testimonial />
        </>
    )
}

export default page