export const metadata = {
    title: "Testimonial  || Ozark Company",
    description: "Generated by create next app",
  };

function page() {
    // const [activeTab, setActiveTab] = useState(1);
    // const handleTabClick = (tabIndex) => {
    //     setActiveTab(tabIndex);
    // };
    return (
        <>
            <div id="content" className="site-content ">
                <div className="page_header_default style_one ">
                    <div className="parallax_cover">
                        <div className="simpleParallax">
                            <img src="/assets/images/page-header-default.jpg" alt="bg_image" className="cover-parallax"/>
                        </div>
                    </div>
                    <div className="page_header_content">
                        <div className="auto-container">
                            <div className="row">
                                <div className="col-md-12">
                                    <div className="banner_title_inner">
                                        <div className="title_page">
                                            Empowering Client Journeys
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-12">
                                    <div className="breadcrumbs creote">
                                        <ul className="breadcrumb m-auto">
                                            <li><a href="index-2.html">Home</a></li>
                                            <li className="active">Empowering Client Journeys</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <section className="testimonial-section testimonial-section project_all filt_style_two filter_enabled">
                    <div className="pd_top_50"></div>
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="fliter_group" style={{textAlign:"center !important"}}>
                                    <ul className="project_filter dark clearfix">
                                        <li data-filter=".project_category-coaching" className="img-fluid current">Financial Automation</li>
                                        <li data-filter=".project_category-human-resources" className="img-fluid">AP/AR Processes</li>
                                        <li data-filter=".project_category-leadership" className="img-fluid">Virtual CFO</li>
                                        <li data-filter=".project_category-leadership" className="img-fluid">Year-End Accounts</li><li data-filter=".project_category-leadership" className="img-fluid">Bookkeeping</li></ul>
                                </div>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-md-4">
                                <div className="testimonial_box type_two">
                                    <div className="upper_content">
                                        <div className="image_box">
                                            <img src="/assets/images/testi-3.png" className="img-fluid" alt="image"/>
                                                <span className="icon-quote"></span>
                                        </div>
                                        <div className="description">
                                            <p>
                                                We hired creote to assist us with refining marketing plans, you
                                                truly understands &amp; gave us very good ideas.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="lower_content clearfix">
                                        <div className="authour_name">
                                            <h2>Ivor Herbert</h2>
                                            <h6>Manager, Airlines</h6>
                                        </div>
                                        <p>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star empty"></i>
                                            <i className="fa fa-star empty"></i>
                                        </p>
                                    </div>

                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="testimonial_box type_two">
                                    <div className="upper_content">
                                        <div className="image_box">
                                            <img src="/assets/images/testi-2.png" className="img-fluid" alt="image"/>
                                                <span className="icon-quote"></span>
                                        </div>
                                        <div className="description">
                                            <p>
                                                I love creote everyone has been great to work with and you’re
                                                all
                                                great partner for company, we thank you ...
                                            </p>
                                        </div>
                                    </div>
                                    <div className="lower_content clearfix">
                                        <div className="authour_name">
                                            <h2>Boris Elbert </h2>
                                            <h6>Green Tech</h6>
                                        </div>
                                        <p>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star empty"></i>
                                            <i className="fa fa-star empty"></i>
                                        </p>
                                    </div>

                                </div>
                            </div>

                            <div className="col-md-4">
                                <div className="testimonial_box type_two">
                                    <div className="upper_content">
                                        <div className="image_box">
                                            <img src="/assets/images/testi-3.png" className="img-fluid" alt="image"/>
                                                <span className="icon-quote"></span>
                                        </div>
                                        <div className="description">
                                            <p>
                                                We hired creote to assist us with refining marketing plans, you
                                                truly understands &amp; gave us very good ideas.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="lower_content clearfix">
                                        <div className="authour_name">
                                            <h2>Ivor Herbert</h2>
                                            <h6>Manager, Airlines</h6>
                                        </div>
                                        <p>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star empty"></i>
                                            <i className="fa fa-star empty"></i>
                                        </p>
                                    </div>

                                </div>
                            </div>
                            <div className="pd_bottom_30"></div>
                            <div className="col-md-4">
                                <div className="testimonial_box type_two">
                                    <div className="upper_content">
                                        <div className="image_box">
                                            <img src="/assets/images/testi-2.png" className="img-fluid" alt="image"/>
                                                <span className="icon-quote"></span>
                                        </div>
                                        <div className="description">
                                            <p>
                                                I love creote everyone has been great to work with and you’re
                                                all
                                                great partner for company, we thank you ...
                                            </p>
                                        </div>
                                    </div>
                                    <div className="lower_content clearfix">
                                        <div className="authour_name">
                                            <h2>Boris Elbert </h2>
                                            <h6>Green Tech</h6>
                                        </div>
                                        <p>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star empty"></i>
                                            <i className="fa fa-star empty"></i>
                                        </p>
                                    </div>

                                </div>
                            </div>
                            <div className="col-md-4">
                                <div className="testimonial_box type_two">
                                    <div className="upper_content">
                                        <div className="image_box">
                                            <img src="/assets/images/testi-3.png" className="img-fluid" alt="image"/>
                                                <span className="icon-quote"></span>
                                        </div>
                                        <div className="description">
                                            <p>
                                                We hired creote to assist us with refining marketing plans, you
                                                truly understands &amp; gave us very good ideas.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="lower_content clearfix">
                                        <div className="authour_name">
                                            <h2>Ivor Herbert</h2>
                                            <h6>Manager, Airlines</h6>
                                        </div>
                                        <p>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star fill"></i>
                                            <i className="fa fa-star empty"></i>
                                            <i className="fa fa-star empty"></i>
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="pd_bottom_90"></div>
                </section>
            </div>

        </>
    )
}

export default page