import React from 'react'
import Service from './Service'
export const metadata = {
  title: "Best Solution || Ozark Company",
  description: "Generated by create next app",
};

function page() {
  return (
<Service/>
  )
}

export default page