

import React from 'react'
export const metadata = {
    title: "Our Team || Ozark Company",
    description: "Generated by create next app",
  };

function page() {
    return (
        <>
            <div id="content" className="site-content ">
                <div className="page_header_default style_one ">
                    <div className="parallax_cover">
                        <div className="simpleParallax">
                            <img src="/assets/images/page-header-default.jpg" alt="bg_image" className="cover-parallax" />
                        </div>
                    </div>
                    <div className="page_header_content">
                        <div className="auto-container">
                            <div className="row">
                                <div className="col-md-12">
                                    <div className="banner_title_inner">
                                        <div className="title_page">
                                            Our Team
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-12">
                                    <div className="breadcrumbs creote">
                                        <ul className="breadcrumb m-auto">
                                            <li><a href="index-2.html">Home</a></li>
                                            <li className="active">Our Team</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <section className="team-intro">
                    <div className="pd_top_90"></div>
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="team_intro_box">
                                    <div className="team_intro_inner">
                                        <div className="image_bg">
                                            <img src="/assets/images/team-intro-bg.jpg" className="img-fluid" alt="image" />
                                        </div>
                                        <div className="team_intro_start">
                                            <div className="row">
                                                <div className="col-lg-8">
                                                    <div className="left_content">
                                                        <div className="title">
                                                            <h6>Strong Team</h6>
                                                            <h1>Foundation of Business</h1>
                                                        </div>
                                                        <div className="quotes">
                                                            <span className="icon-quote"></span>
                                                            <h5>Teamwork is the secret that <br /> makes common people achieve <br />
                                                                uncommon results.</h5>
                                                        </div>

                                                    </div>
                                                </div>
                                                <div className="col-lg-4">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="image_right">
                                        <img src="/assets/images/team-head-1.png" alt="image" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="image-section">
                    <div className="pd_top_90"></div>
                    <div className="container">
                        <div className="row">
                            <div className="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4 mb-lg-4 mb-xl-0">
                                <div className="icon_box_all style_four">
                                    <div className="icon_content icon_imgs">
                                        <div className="icon">
                                            <img src="/assets/images/icon-img-n-3.png" className="img-fluid svg_image" alt="icon png" />
                                            <img src="/assets/images/shape-1-small.png" className="shape" alt="img" />
                                        </div>
                                        <div className="txt_content">
                                            <h3>
                                                <a href="#" target="_blank" rel="nofollow">Professionally<br />trained</a>
                                            </h3>
                                            <p>Holds in these matters principles all selection right rejects.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4 mb-lg-4 mb-xl-0">
                                <div className="icon_box_all style_four">
                                    <div className="icon_content icon_imgs ">
                                        <div className="icon">
                                            <img src="/assets/images/icon-img-n-4.png" className="img-fluid svg_image" alt="icon png" />
                                            <img src="/assets/images/shape-1-small.png" className="shape" alt="img" />
                                        </div>
                                        <div className="txt_content">
                                            <h3>
                                                <a href="#" target="_blank" rel="nofollow">Team is available 7<br />days a week</a>
                                            </h3>
                                            <p>No one rejects dislikes avoids sure but because those who do.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-4 mb-lg-4 mb-xl-0">
                                <div className="icon_box_all style_four">
                                    <div className="icon_content icon_imgs ">
                                        <div className="icon">
                                            <img src="/assets/images/icon-img-n-5.png" className="img-fluid svg_image" alt="icon png" />
                                            <img src="/assets/images/shape-1-small.png" className="shape" alt="img" />
                                        </div>
                                        <div className="txt_content">
                                            <h3>
                                                <a href="#" target="_blank" rel="nofollow">Focused on achieving results</a>
                                            </h3>
                                            <p>Loves or pursues or desires obtain of itself because it is pain.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div className="icon_box_all style_four">
                                    <div className="icon_content icon_imgs">
                                        <div className="icon">
                                            <img src="/assets/images/fun-2.png" className="img-fluid svg_image" alt="icon png" />
                                            <img src="/assets/images/shape-1-small.png" className="shape" alt="img" />
                                        </div>
                                        <div className="txt_content">
                                            <h3>
                                                <a href="#" target="_blank" rel="nofollow">Exceeds our client’s expectations</a>
                                            </h3>
                                            <p>Trivial example which of us ever all undertakes laborious.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="pd_bottom_70"></div>
                </section>
                <section className="team-section bg_light_1">
                    <div className="pd_top_90"></div>
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="title_all_box style_one text-center dark_color">
                                    <div className="title_sections">
                                        <div className="before_title">Dedicated Team</div>
                                        <h2>Professional Individuals</h2>
                                    </div>
                                    <div className="pd_bottom_20"></div>
                                </div>
                            </div>
                        </div>
                        <div className="row">

                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-1.jpg" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Director </span>
                                                <h6>Amelia Margaret</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-2.jpg" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Team Leader </span>
                                                <h6>Andrew Cameron</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-3.png" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Manager </span>
                                                <h6>Sofia Charlotte</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-4.jpg" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Consultant </span>
                                                <h6>Felix Ebenezer</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-5.png" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Consultant </span>
                                                <h6>Grace Savannah</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                <div className="team_box style_one">
                                    <div className="team_box_outer">
                                        <div className="member_image">
                                            <img src="/assets/images/team/team-6.png" alt="team image" />
                                        </div>
                                        <div className="about_member">
                                            <div className="share_media">
                                                <ul className="first">
                                                    <li className="text">Share</li>
                                                    <li><i className="fa fa-share-alt"></i></li>
                                                </ul>
                                                <ul>
                                                    <li className="shar_alt"><i className="fa fa-share-alt"></i></li>
                                                    <li><a href="#"> <i className="fa fa-facebook"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-twitter"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-skype"> </i> </a></li>
                                                    <li><a href="#"> <i className="fa fa-instagram"> </i> </a></li>
                                                </ul>
                                            </div>
                                            <div className="authour_details">
                                                <span>Consultant </span>
                                                <h6>Hal Drummond</h6>
                                                <div className="button_view">
                                                    <a href="#" target="_blank" rel="nofollow" className="theme-btn one"> View Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="pd_bottom_70"></div>
                </section>
            </div>
        </>
    )
}

export default page