import React from 'react'
import CaseStudy from './CaseStudy';

export const metadata = {
    title: "Case Study  || Ozark Company",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <CaseStudy />
    )
}

export default page