import React from 'react'
export const metadata = {
    title: "Case Study  || Ozark Company",
    description: "Generated by create next app",
  };
function page() {
    return (
        <>
            <div id="content" className="site-content ">
                <div className="page_header_default style_one ">
                    <div className="parallax_cover">
                        <div className="simpleParallax">
                            <img src="/assets/images/page-header-default.jpg" alt="bg_image" className="cover-parallax"/>
                        </div>
                    </div>
                    <div className="page_header_content">
                        <div className="auto-container">
                            <div className="row">
                                <div className="col-md-12">
                                    <div className="banner_title_inner">
                                        <div className="title_page">
                                            Case Studies
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-12">
                                    <div className="breadcrumbs creote">
                                        <ul className="breadcrumb m-auto">
                                            <li><a href="index-2.html">Home</a></li>
                                            <li className="active">Case Studies</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <section className="project-section">
                    <div className="pd_top_80"></div>
                    <div className="container">
                        <div className="project_all filt_style_eight filter_enabled">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="fliter_group" style={{textAlign:"center!important"}}>
                                        <ul className="project_filter dark clearfix">
                                            <li data-filter="*" className="current">View All</li>
                                            <li data-filter=".project_category-coaching" className="img-fluid current">Financial Automation</li>
                                            <li data-filter=".project_category-human-resources" className="img-fluid">AP/AR Processes</li>
                                            <li data-filter=".project_category-leadership" className="img-fluid">Virtual CFO</li>
                                            <li data-filter=".project_category-leadership" className="img-fluid">Year-End Accounts</li><li data-filter=".project_category-leadership" className="img-fluid">Bookkeeping</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div className="project_container clearfix" style={{position: "relative", height: "916px"}}>
                                <div className="row clearfix">
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-coaching" style={{position: "absolute", left: "0px", top: "0px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="746" height="497" src="/assets/images/projects/project-2-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img"/> <a data-fancybox="gallery" href="/assets/images/projects/project-2-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Complex Dismissal for a Small
                                                        Company</a></h2>
                                                    <p>coaching</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-human-resources" style={{position: "absolute", left: "380px", top: "0px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="742" height="495" src="/assets/images/projects/project-3-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img"/> <a data-fancybox="gallery" href="/assets/images/projects/project-3-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Essential Steps to Writing Job
                                                        Description</a></h2>
                                                    <p>human-resources</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-leadership" style={{position: "absolute", left: "760px", top: "0px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="999" height="665" src="/assets/images/projects/project-1-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img" loading="lazy"/> <a data-fancybox="gallery" href="/assets/images/projects/project-1-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Company Values &amp; The
                                                        Relationship</a></h2>
                                                    <p>leadership</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-pre-sale" style={{position: "absolute", left: "0px", top: "443px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="827" height="465" src="/assets/images/projects/project-4-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img" loading="lazy" srcSet="/assets/images/projects/project-4-img.jpg 827w, /assets/images/projects/project-4-img-600x337.jpg 600w, /assets/images/projects/project-4-img-300x169.jpg 300w, /assets/images/projects/project-4-img-768x432.jpg 768w" sizes="(max-width: 827px) 100vw, 827px"/> <a data-fancybox="gallery" href="/assets/images/projects/project-4-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Time HR Prepares Plastic
                                                        Contract Manufacturer</a></h2>
                                                    <p>pre-sale</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-recruiting" style={{position: "absolute", left: "760px", top: "443px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="731" height="488" src="assets/images/projects/project-6-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img" loading="lazy" srcSet="/assets/images/projects/project-6-img.jpg 731w, /assets/images/projects/project-6-img-600x401.jpg 600w, /assets/images/projects/project-6-img-300x200.jpg 300w" sizes="(max-width: 731px) 100vw, 731px"/> <a data-fancybox="gallery" href="/assets/images/projects/project-6-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Shared Time Human Resources
                                                        Management</a></h2>
                                                    <p>recruiting</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="project-wrapper grid-item col-xl-4 col-lg-6 col-md-6 col-sm-12 col-xs-12  project_category-values" style={{position: "absolute", left: "380px", top: "473px"}}>
                                        <div className="project_post style_eight">
                                            <div className="inner_box">
                                                <div className="image_box ">
                                                    <img width="887" height="591" src="/assets/images/projects/project-5-img.jpg" className="attachment-creote_project_caro_image_style_one size-creote_project_caro_image_style_one wp-post-image" alt="img" loading="lazy" srcSet="/assets/images/projects/project-5-img.jpg 887w, /assets/images/projects/project-5-img-600x400.jpg 600w, /assets/images/projects/project-5-img-300x200.jpg 300w, /assets/images/projects/project-5-img-768x512.jpg 768w" sizes="(max-width: 887px) 100vw, 887px"/> <a data-fancybox="gallery" href="/assets/images/projects/project-5-img.jpg">
                                                        <span className="icon-plus zoom_icon"></span>
                                                    </a>
                                                </div>
                                                <div className="content_box ">
                                                    <h2 className="title_pro"><a href="#" rel="bookmark">Six Essential Steps To Writing
                                                        Successful Job</a></h2>
                                                    <p>values</p>
                                                    <a href="#" className="arrow_btn "><span className="icon-right-arrow-long"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="pd_bottom_80"></div>
                </section>
            </div>
        </>
    )
}

export default page